config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'callbacks' }
  
  devise_scope :user do
    get '/users/sign_in', to: 'devise/sessions#new'
    post '/users/sign_in', to: 'devise/sessions#create'
    get '/users/sign_up', to: 'devise/sessions#new'
    post '/users/sign_up', to: 'devise/sessions#create'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  get 'games/search_term/:search_term', to: 'games#index'

  get '/users/:id', to: 'users#show'

  
  get '/games/new', to: 'games#new'

  root to: 'welcome#home'

  resources :categories do 
    resources :games, only: [:new, :create, :update, :index]
  end
  resources :games

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :games
    has_many :users, through: :games

    accepts_nested_attributes_for :games
    
    validates :name, uniqueness: true
end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :category
    belongs_to :user

    scope :multiplayergames, -> { where("online_multiplayer = true") }

    #scope :awesomegames, -> { where("hours_played > 100") }
    #<%= link_to 'Awesome Games', '/games/search_term/hours_played', class: "btn btn-secondary btn-sm text-white" %>

    validates :title, presence: true

    accepts_nested_attributes_for :category, reject_if: :all_blank
end

app/models/tournament.rb
class Tournament < ApplicationRecord
    belongs_to :game
    has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  has_many :games
  has_many :categories, through: :games
  accepts_nested_attributes_for :games

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email 
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :current_user
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end 
end 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!

    def index
        @categories = current_user.categories.sort_by do |category| 
            #binding.pry
            category.games.count
        end
        @categories = @categories.reverse.uniq
    end

    def show
        @categories = current_user.categories.find_by(id: params[:id])
        render :show
    end 

    def new
        @category = current_user.categories.new(id: params[:id])
        @game = @category.games.build
    end

    def create
        @category = current_user.categories.build(category_params)
        
        if @category.save
            redirect_to category_path(@category)
        else
            render :new 
        end 
    end

    def edit 
        @category = current_user.categories.find_by(id: params[:id])
    end 

    def update
        @category = current_user.categories.update(category_params)

        if @category
            redirect_to category_path
        else 
            render :edit
        end 
    end 

    def delete
        @category = current_user.categories.find_by(id: params[:id])
        
        if @category
            @category.destroy 
        end 
        
        redirect_to categories
    end 


    private 

    def category_params
        params.require(:category).permit(:name, :user_id, :category_id)
    end 
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :authenticate_user!

    def index
        if params[:category_id]
            @category = current_user.categories.find_by(id: params[:category_id])
            @games = @category.games
        elsif params[:search_term]
            if params[:search_term] = "multiplayergames"
                @games = current_user.games.multiplayergames
            # else params[:search_term] = "awesomegames"
            #     @games = current_user.games.awesomegames
            end
        else
            @games = current_user.games.order(:title)
        end
    end

    def show
        @game = current_user.games.find_by(id: params[:id])
        if !@game
            redirect_to games_path
        end
    end

    def new
        if params[:category_id] && @category = current_user.categories.find_by(id: params[:category_id])
            @game = @category.games.build
        else
            @game = current_user.games.build
        end
    end

    def edit
        @game = current_user.games.find_by(id: params[:id])
    end

    def create
        @game = current_user.games.build(game_params)
        if @game.save
            redirect_to @game
        else
            render :new
        end
    end

    def update
        @game = current_user.games.find_by(id: params[:id])
        if @game.update(game_params)
            redirect_to @game
        else
            render :edit 
        end
    end

    def destroy
        @game = current_user.games.find_by(id: params[:id])
        if @game
            @game.destroy 
        end
        redirect_to games_path
    end

    private

    def game_params 
        params.require(:game).permit(:title, :release_year, :hours_played, :online_multiplayer, :campaign, :campaign_completed, :user_id, :category_id, category_attributes: [ :name ])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def signup_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.find_by(name: params[:user][:name])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user), notice: "Welcome to your Gaming Catalog!"
        else 
            redirect_to new_user_session_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/categories/_form.html.erb
<h1>New Category</h1>
<% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @category do |f| %>
    <b>Category</b>
    <b><%= f.label :name %><b>
    <%= f.text_field :name %><br>
    <br>
    <%= f.submit %>
<% end %>

app/views/categories/index.html.erb
<ul>
<% @categories.each do |cat| %>
    <li><%= link_to cat.name, category_games_path(cat, @game) %></li><br>
<% end %>
</ul>
<button><%= link_to 'Add Category', new_category_path %></button>
<br>
<br>
<button><%= link_to 'View All Games', games_path %></button>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

    <h3>My <%= @category.name %> Games:</h3>
    <button><%= link_to 'See Games', category_games_path(@category) %></button>

<br>
<br>
<button><%= link_to 'Back', root_path %></button>
<br>
<button><%= link_to 'Delete Category', @category, method: :delete %></button>

app/views/category/index.html.erb
<ul>
<% @categories.each do |cat| %>
    <li><%= link_to cat.name, category_games_path(cat, @game) %></li><br>
<% end %>
</ul>

app/views/category/show.html.erb
<h1><%= @category.name %></h1>

    <h3>Games:</h3>
    <button><%= link_to 'See Games', category_games_path(@category) %></button>

<br>
<br>
<button><%= link_to 'Back', root_path %></button>
<button><%= link_to 'Delete Category', @category, method: :delete %></button>

app/views/game/_form.html.erb
<h3>Add a Game To Your Library: </h3>
<hr>
<h4>Enter Your Game Information: </h4>


<%= form_for(@game) do |g| %>
    <div class="field_with_errors">
        <% if @game.errors.any? %>
            <h3>Errors:</h3>
            <ul>
                <% @game.errors.full_messages.each do |m| %>
                <li><%= m %></li>
                <% end %>
            </ul>
        <% end %>
    </div>

    <%= f.label "Game" %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :release_year %>
    <%= f.text_field :release_year %>
    <br>
    <%= f.label :hours_played %>
    <%= f.text_field :hours_played %>
    <br>
    <%= f.label :online_multiplayer %>
    <%= f.text_field :online_multiplayer %>
    <br>
    <%= f.label :campaign %>
    <%= f.text_field :campaign %>
    <br>
    <%= f.label :campaign_completed %>
    <%= f.text_field :campaign_completed %>
    <br>


<h4>Category Info: </h4>
    <% if @category %>
        <%= f.hidden_field :category_id %>
    <% else %>
       <p> Select from an exisiting category
        <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: "Choose A Category"  %></p>
        <p> or create a new category =>
        <%= f.fields_for :category, @game.build_category do |game_category| %>
            <%= game_category.label "Category" %>
            <%= game_category.text_field :name %>
        <% end %></p>
    <% end %>
    <%= f.submit %>
<% end %>

app/views/games/_form.html.erb
<h3>Add a Game To Your Library: </h3>
<hr>
<h4>Enter Your Game Information: </h4>


<%= form_for(@game) do |f| %>
    <div class="field_with_errors">
        <% if @game.errors.any? %>
            <h3>Errors:</h3>
            <ul>
                <% @game.errors.full_messages.each do |m| %>
                <li><%= m %></li>
                <% end %>
            </ul>
        <% end %>
    </div>

    <%= f.label "Game" %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :release_year %>
    <%= f.text_field :release_year %>
    <br>
    <%= f.label :hours_played %>
    <%= f.text_field :hours_played %>
    <br>
    <%= f.label :online_multiplayer %>
        <%= f.label 'online_multiplayer_true', 'Yes' %>
        <%= f.radio_button :online_multiplayer, true %>
    
        <%= f.label 'online_multiplayer_false', 'No' %>
        <%= f.radio_button :online_multiplayer, false %>
    <br>
    <%= f.label :campaign %>
        <%= f.label 'campaign_true', 'Yes' %>
        <%= f.radio_button :campaign, true %>
    
        <%= f.label 'campaign_false', 'No' %>
        <%= f.radio_button :campaign, false %>
    <br>
    <%= f.label :campaign_completed %>
        <%= f.label 'campaign_completed_true', 'Yes' %>
        <%= f.radio_button :campaign_completed, true %>
    
        <%= f.label 'campaign_completed_false', 'No' %>
        <%= f.radio_button :campaign_completed, false %>
    <br>


<h4>Category Info: </h4>
    <% if @category %>
    <h5> <%= @category.name %> Category </h5>
        <%= f.hidden_field :category_id %>
    <% else %>
       <p> Select from an exisiting category
        <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: "Choose A Category"  %></p>
        <p> or create a New Category Here
        <%= f.fields_for :category, @game.build_category do |game_category| %>
            <%= game_category.text_field :name %>
        <% end %></p>
    <% end %>
    <%= f.submit %>
<% end %>

app/views/games/edit.html.erb
<%= render 'form' %>

app/views/games/index.html.erb
<% if @category %>
    <hr>
    <h2> <%= @category.name %> Games: </h2>
<% else %>
    <hr>
    <h2>My Games: </h2>
<% end %>

<% @games.each do |g| %>
    <%= link_to g.title, game_path(g) %><br>
<% end %>
<br>
<br>
<% if @category %>
    <button><%= link_to "Add Game",  new_category_game_path(@category) %></button>
<% else %>
    <button><%= link_to "Add Game",  new_game_path %></button>
<% end %>
<br>
<br>
<button><%= link_to 'View Categories', categories_path %></button>
<br>
<br>
<%= link_to 'Multiplayer Games', '/games/search_term/online_multiplayer', class: "btn btn-secondary btn-sm text-white" %>

app/views/games/show.html.erb
<h1><%= @game.title %></h1>

<p>Release Year:</p>
<li><%= @game.release_year %></li><br>

<p>Hours Played:</p>
<li><%= @game.hours_played %></li><br>

<p>Online Multiplayer:</p>
<li><%= @game.online_multiplayer %></li><br>

<p>Campaign:</p>
<li><%= @game.campaign %></li><br>

<p>Campaign Completed?:</p>
<li><%= @game.campaign_completed %></li><br>

<p>Category:</p>
<li><%= @game.category.name %></li><br>

<button><%= link_to 'Edit', edit_game_path %></button>
<br>
<br>
<br>
<%= button_to 'Delete Game', game_path(@game), method: :delete %>
<br>
<br>
<br>
<button><%= link_to 'Back', games_path %></button>

app/views/layouts/_nav.html.erb
<nav>
    <ul>
        <% if user_signed_in? %>
            <li><button><%= link_to 'Home', root_path %></button></li>
            <li><button><%= link_to 'Edit Account', edit_user_registration_path %></button></li>
            <li><button><%= link_to 'Log Out', destroy_user_session_path, method: 'delete' %></button></li>
        <% end %>
    </ul>
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/welcome/home.html.erb
<h1>Welcome To Your Gaming Catalog!</h1>
<h3>This application allows you to create a record of games that you have played or currently playing!</h3>
<% if !user_signed_in? %>
    <h3><%= link_to "Sign Up", new_user_registration_path %> or <%= link_to "Sign In", new_user_session_path %></h3>
<% end %>

<% if user_signed_in? %>
    <h3><button><%= link_to "Add Game", new_game_path %></button></h3>
<% end %>

<nav>
    <ul>
        <% if !user_signed_in? %>
            <li><button><%= link_to 'Sign Up', new_user_registration_path %></button></li>
            <li><button><%= link_to 'Log In', new_user_session_path %></button></li>
        <% else %>
            <li><button><%= link_to 'View Current Games', games_path %></button></li>
            <br>
        <% end %>
    </ul>
</nav>   